#spring.application.name=backend
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/lafenice_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: happy

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true

jwt:
  #임시패스워드키_swj_project_lafenice_2026_safe_key_secure_point
  secret: 7J6E7Iuc7Yyo7Iqk7JuM65Oc7YKkX3N3al9wcm9qZWN0X2xhZmVuaWNlXzIwMjZfc2FmZV9rZXlfc2VjdXJlX3BvaW50
  # 토큰 유효 시간: 1시간 (3600000 밀리초)
  expiration-time: 3600000
  # Refresh Token 유효 시간: 14일 (1209600000 밀리초)
  refresh-expiration-time: 1209600000